<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chính sách quyền riêng tư</title>
</head>
<body>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:32px;font-family:"Arial",sans-serif;color:#636E75;'>Ch&iacute;nh s&aacute;ch quyền ri&ecirc;ng tư</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;text-align:center;line-height:normal;background:white;'><u><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>NGUY&Ecirc;N TẮC V&Ecirc;̀ QUY&Ecirc;̀N RI&Ecirc;NG TƯ CỦA CFS3DOC</span></u></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>CFS3Doc r&acirc;́t coi trọng quy&ecirc;̀n ri&ecirc;ng tư. Năm nguy&ecirc;n tắc dưới đ&acirc;y là cơ sở cho phương pháp ti&ecirc;́p c&acirc;̣n của chúng t&ocirc;i trong vi&ecirc;̣c t&ocirc;n trọng quy&ecirc;̀n ri&ecirc;ng tư của quý khách:</span></p>
<ol start="1" type="1" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Chúng t&ocirc;i đánh giá cao ni&ecirc;̀m tin quý khách dành cho chúng t&ocirc;i khi quý khách cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n cho chúng t&ocirc;i. Chúng t&ocirc;i sẽ lu&ocirc;n sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách m&ocirc;̣t cách ch&acirc;n thực và xứng đáng với ni&ecirc;̀m tin đó.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Quý khách có quy&ecirc;̀n tìm hi&ecirc;̉u th&ocirc;ng tin v&ecirc;̀ cách chúng t&ocirc;i sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách. Chúng t&ocirc;i sẽ lu&ocirc;n th&ocirc;ng báo rõ ràng với quý khách v&ecirc;̀ những th&ocirc;ng tin chúng t&ocirc;i thu th&acirc;̣p, những vi&ecirc;̣c chúng t&ocirc;i làm với th&ocirc;ng tin đó, đ&ocirc;́i tượng chúng t&ocirc;i chia sẻ và người quý khách c&acirc;̀n li&ecirc;n lạc trong trường hợp có b&acirc;́t kỳ mối quan ngại nào.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>N&ecirc;́u quý khách có b&acirc;́t kỳ mối quan ngại nào v&ecirc;̀ cách thức chúng t&ocirc;i sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách, chúng t&ocirc;i sẵn sàng hợp tác với quý khách đ&ecirc;̉ nhanh chóng giải quy&ecirc;́t những mối quan ngại đó.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Chúng t&ocirc;i sẽ thực hi&ecirc;̣n t&acirc;́t cả c&aacute;c bước hợp l&yacute; đ&ecirc;̉ bảo v&ecirc;̣ th&ocirc;ng tin của quý khách kh&ocirc;ng bị lạm dụng và bảo m&acirc;̣t th&ocirc;ng tin đó.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Chúng t&ocirc;i sẽ tu&acirc;n thủ theo t&acirc;́t cả các lu&acirc;̣t và quy định bảo v&ecirc;̣ dữ li&ecirc;̣u áp dụng đ&ocirc;̀ng thời sẽ hợp tác với các cơ quan bảo v&ecirc;̣ dữ li&ecirc;̣u. N&ecirc;́u kh&ocirc;ng có lu&acirc;̣t bảo v&ecirc;̣ dữ li&ecirc;̣u, chúng t&ocirc;i sẽ hành đ&ocirc;̣ng theo các nguy&ecirc;n tắc được c&ocirc;ng nh&acirc;̣n r&ocirc;̣ng rãi v&ecirc;̀ bảo v&ecirc;̣ dữ li&ecirc;̣u.</span></li>
</ol>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;text-align:center;line-height:normal;background:white;'><u><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>CHÍNH SÁCH V&Ecirc;̀ QUY&Ecirc;̀N RI&Ecirc;NG TƯ CỦA CFS3DOC</span></u></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><em><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>L&acirc;̀n C&acirc;̣p Nh&acirc;̣t G&acirc;̀n Đ&acirc;y Nh&acirc;́t: Tháng 9 Năm 2023</span></em></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>CFS3Doc cam k&ecirc;́t bảo v&ecirc;̣ quy&ecirc;̀n ri&ecirc;ng tư của quý khách và đảm bảo bảo v&ecirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách. Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này n&ecirc;u rõ những th&ocirc;ng tin cá nh&acirc;n chúng t&ocirc;i thu th&acirc;̣p và cách thức chúng t&ocirc;i sử dụng, ti&ecirc;́t l&ocirc;̣ và bảo vệ th&ocirc;ng tin đó.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Đ&ocirc;́i tượng áp dụng của Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này là gì?</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này áp dụng cho th&ocirc;ng tin cá nh&acirc;n được CFS3Doc thu th&acirc;̣p li&ecirc;n quan đ&ecirc;́n các dịch vụ m&agrave; Tập đo&agrave;n cung c&acirc;́p. Tìm hi&ecirc;̉u th&ecirc;m th&ocirc;ng tin v&ecirc;̀ CFS3Doc tại địa chỉ <a href="http://tailieu.thpthahoacfs3.click/ve-chung-toi"><span style="color:#EE8F08;">http://tailieu.thpthahoacfs3.click//ve-chung-toi.</span></a> Trang này trình bày th&ocirc;ng tin được thu th&acirc;̣p theo hình thức ngoại tuy&ecirc;́n và các trung t&acirc;m chăm sóc khách hàng của chúng t&ocirc;i, các chi&ecirc;́n dịch tiếp thị trực ti&ecirc;́p, hình thức rút thăm trúng thưởng và các cu&ocirc;̣c thi, cũng như hình thức thu th&acirc;̣p trực tuy&ecirc;́n th&ocirc;ng qua các trang web của chúng t&ocirc;i, các trang uy tín v&ecirc;̀ c&aacute;c nền tảng và chương trình ứng dụng của b&ecirc;n thứ ba được truy c&acirc;̣p hay sử dụng th&ocirc;ng qua những trang web hoặc nền tảng của b&ecirc;n thứ ba đó được CFS3Doc hoặc đại di&ecirc;̣n của CFS3Doc đi&ecirc;̀u hành (&ldquo;<strong>Các Trang Web của CFS3Doc</strong>&rdquo;). Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này dưới đ&acirc;y được k&ecirc;́t hợp và tạo thành m&ocirc;̣t ph&acirc;̀n của các đi&ecirc;̀u khoản và đi&ecirc;̀u ki&ecirc;̣n sử dụng Trang Web CFS3Doc ứng dụng. Đ&ecirc;̉ bi&ecirc;́t th&ocirc;ng tin v&ecirc;̀ vi&ecirc;̣c CFS3Doc chịu trách nhi&ecirc;̣m bảo vệ th&ocirc;ng tin cá nh&acirc;n của quý khách, xin xem <a href="http://tailieu.thpthahoacfs3.click/private-policy#rights"><strong><span style="color:#EE8F08;">Quy&ecirc;̀n bảo m&acirc;̣t của quý khách và người c&acirc;̀n li&ecirc;n h&ecirc;̣</span></strong></a> dưới đ&acirc;y.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này kh&ocirc;ng áp dụng đ&ocirc;́i với:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>th&ocirc;ng tin thu thập được từ các trang web, các nền tảng và/hoặc ứng dụng b&ecirc;n thứ ba (&ldquo;<strong>Các Trang Web B&ecirc;n Thứ Ba</strong>&rdquo;) mà chúng t&ocirc;i kh&ocirc;ng ki&ecirc;̉m soát;</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>th&ocirc;ng tin do các Trang Web B&ecirc;n Thứ Ba thu th&acirc;̣p mà quý khách có th&ecirc;̉ truy c&acirc;̣p qua các đường link vào các Trang Web của CFS3Doc; hay</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>băng r&ocirc;n quảng cáo, chương trình rút thăm trúng thưởng và các chương trình quảng cáo hay khuy&ecirc;́n m&atilde;i khác tr&ecirc;n các Trang Web của B&ecirc;n Thứ Ba mà chúng t&ocirc;i có th&ecirc;̉ tài trợ hay tham gia.</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Những Trang Web B&ecirc;n Thứ Ba này có th&ecirc;̉ có những chính sách v&ecirc;̀ quy&ecirc;̀n ri&ecirc;ng tư, các đi&ecirc;̀u khoản và đi&ecirc;̀u ki&ecirc;̣n ri&ecirc;ng của mình. Chúng t&ocirc;i khuy&ecirc;́n khích quý khách n&ecirc;n đọc trước khi sử dụng các Trang Web B&ecirc;n Thứ Ba này.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Sự đ&ocirc;̀ng ý của quý khách</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>CFS3Doc sẽ kh&ocirc;ng thu th&acirc;̣p, sử dụng hay ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách mà kh&ocirc;ng được sự đ&ocirc;̀ng ý của quý khách. Trong h&acirc;̀u h&ecirc;́t trường hợp, chúng t&ocirc;i sẽ xin phép quý khách m&ocirc;̣t cách rõ ràng nhưng, trong m&ocirc;̣t s&ocirc;́ trường hợp, chúng t&ocirc;i có th&ecirc;̉ suy lu&acirc;̣n v&ecirc;̀ sự đ&ocirc;̀ng ý từ những hành đ&ocirc;̣ng và hành vi của quý khách. Bằng cách sử dụng Trang Web CFS3Doc, quý khách đ&ocirc;̀ng ý cho phép CFS3Doc thu th&acirc;̣p, sử dụng và ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách theo Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ y&ecirc;u c&acirc;̀u quý khách cung c&acirc;́p sự đ&ocirc;̀ng thu&acirc;̣n b&ocirc;̉ sung n&ecirc;́u c&acirc;̀n sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách cho các mục đích kh&ocirc;ng được trình bày trong Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này. Quý khách kh&ocirc;ng bắt bu&ocirc;̣c phải đ&ocirc;̀ng ý, tuy nhi&ecirc;n n&ecirc;́u quý khách quy&ecirc;́t định kh&ocirc;ng đ&ocirc;̀ng ý thì khi đ&oacute; quý khách có th&ecirc;̉ bị hạn ch&ecirc;́ tham gia vào m&ocirc;̣t s&ocirc;́ hoạt đ&ocirc;̣ng. N&ecirc;́u quý khách đ&ocirc;̀ng ý b&ocirc;̉ sung, các đi&ecirc;̀u khoản của sự đ&ocirc;̀ng ý đ&oacute; sẽ được áp dụng trong trường hợp có b&acirc;́t kỳ xung đ&ocirc;̣t nào với các đi&ecirc;̀u khoản của Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>N&ecirc;́u quý khách kh&ocirc;ng đ&ocirc;̀ng ý với vi&ecirc;̣c thu th&acirc;̣p, sử dụng và ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách theo cách này, vui lòng kh&ocirc;ng sử dụng các Trang Web CFS3Doc hoặc quý khách phải cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n cho CFS3Doc.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i thu th&acirc;̣p những th&ocirc;ng tin nào?</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Trong Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này, &ldquo;th&ocirc;ng tin cá nh&acirc;n&rdquo; của quý khách có nghĩa là th&ocirc;ng tin hay mẩu th&ocirc;ng tin có th&ecirc;̉ giúp nh&acirc;̣n di&ecirc;̣n ra quý khách. V&ecirc;̀ cơ bản, đi&ecirc;̀u này bao g&ocirc;̀m những th&ocirc;ng tin như họ t&ecirc;n, địa chỉ, t&ecirc;n đăng nh&acirc;̣p, hình đại di&ecirc;̣n, địa chỉ email và s&ocirc;́ đi&ecirc;̣n thoại, nhưng cũng có th&ecirc;̉ bao g&ocirc;̀m các th&ocirc;ng tin khác chẳng hạn như địa chỉ IP, thói quen mua sắm, sở thích và th&ocirc;ng tin v&ecirc;̀ phong cách sống hay sở thích của quý khách chẳng hạn như sở thích ri&ecirc;ng và m&ocirc;́i quan t&acirc;m. Chúng t&ocirc;i có th&ecirc;̉ thu th&acirc;̣p th&ocirc;ng tin cá nh&acirc;n của qu&yacute; kh&aacute;ch từ nhi&ecirc;̀u ngu&ocirc;̀n khác nhau, bao g&ocirc;̀m:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'><a href="http://tailieu.thpthahoacfs3.click/private-policy#OLE_LINK4"><span style="color:#EE8F08;">Th&ocirc;ng tin quý khách cung c&acirc;́p trực ti&ecirc;́p cho chúng t&ocirc;i</span></a></span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ trực ti&ecirc;́p thu th&acirc;̣p th&ocirc;ng tin v&ecirc;̀ quý khách n&ecirc;́u quý khách cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n cho chúng t&ocirc;i, chẳng hạn như khi quý khách đăng ký tham gia chương trình rút thăm trúng thưởng hay các cu&ocirc;̣c thi, đăng k&yacute; đ&ecirc;̉ nh&acirc;̣n th&ocirc;ng tin, sử dụng đơn xin tham gia, mua sản ph&acirc;̉m hay dịch vụ từ chúng t&ocirc;i, đi&ecirc;̀n vào bảng đi&ecirc;̀u tra, hay đưa ra lời nh&acirc;̣n xét hay y&ecirc;u c&acirc;̀u. Những loại th&ocirc;ng tin chúng t&ocirc;i có th&ecirc;̉ thu th&acirc;̣p trực ti&ecirc;́p từ quý khách bao g&ocirc;̀m:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>t&ecirc;n của quý khách</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>địa chỉ email</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>t&ecirc;n đăng nhập</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>s&ocirc;́ đi&ecirc;̣n thoại</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>tu&ocirc;̉i</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>ngày sinh</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>giới tính</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>n&ocirc;̣i dung do người dùng khởi tạo, các bài đăng và các n&ocirc;̣i dung khác quý khách n&ocirc;̣p cho các Trang Web CFS3Doc</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>b&acirc;́t kỳ th&ocirc;ng tin cá nh&acirc;n nào khác mà quý khách tự nguyện cung c&acirc;́p cho chúng t&ocirc;i</span></li>
    </ul>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'><a href="http://tailieu.thpthahoacfs3.click/private-policy#OLE_LINK4"><span style="color:#EE8F08;">Th&ocirc;ng tin chúng t&ocirc;i tự đ&ocirc;̣ng thu th&acirc;̣p khi quý khách sử dụng các Trang Web CFS3Doc</span></a></span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i sử dụng cookies và các c&ocirc;ng cụ khác (chẳng hạn như c&ocirc;ng cụ ph&acirc;n tích web và thẻ đi&ecirc;̉m ảnh) đ&ecirc;̉ tự đ&ocirc;̣ng thu th&acirc;̣p th&ocirc;ng tin v&ecirc;̀ quý khách khi quý khách sử dụng các Trang Web CFS3Doc, t&ugrave;y theo các đi&ecirc;̀u khoản của Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này và các lu&acirc;̣t và quy định bảo vệ dữ li&ecirc;̣u áp dụng. Những loại th&ocirc;ng tin chúng t&ocirc;i có th&ecirc;̉ thu th&acirc;̣p tự đ&ocirc;̣ng bao g&ocirc;̀m:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>th&ocirc;ng tin v&ecirc;̀ ki&ecirc;̉u b&ocirc;̣ trình duy&ecirc;̣t quý khách sử dụng</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>chi ti&ecirc;́t v&ecirc;̀ các trang web mà quý khách đã xem</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>t&ecirc;n người dùng, hình đại di&ecirc;̣n, giới tính, mạng của quý khách và b&acirc;́t kỳ th&ocirc;ng tin nào khác mà quý khách chọn đ&ecirc;̉ chia sẻ khi dùng các Trang Web B&ecirc;n Thứ Ba (chẳng hạn khi quý khách dùng chức năng &ldquo;Like&rdquo; (thích) tr&ecirc;n Facebook hay chức năng +1 tr&ecirc;n Google+)</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Các trang web quý khách đã ghé thăm trước khi truy c&acirc;̣p vào Trang Web CFS3Doc</span></li>
    </ul>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>H&acirc;̀u h&ecirc;́t các b&ocirc;̣ trình duy&ecirc;̣t internet được thi&ecirc;́t l&acirc;̣p ban đ&acirc;̀u đ&ecirc;̀u ch&acirc;́p nh&acirc;̣n cookies. Quý khách có th&ecirc;̉ thay đ&ocirc;̉i thiết lập đ&ecirc;̉ chặn các cookies hoặc cảnh báo quý khách khi các cookies được gửi tới thi&ecirc;́t bị của quý khách. N&ecirc;́u quý khách tắt cookies, đi&ecirc;̀u này sẽ ảnh hưởng đ&ecirc;́n trải nghi&ecirc;̣m của quý khách tr&ecirc;n các Trang Web CFS3Doc.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách như th&ecirc;́ nào?</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ cải ti&ecirc;́n sản ph&acirc;̉m của chúng t&ocirc;i và n&acirc;ng cao trải nghi&ecirc;̣m của quý khách tr&ecirc;n các Trang Web CFS3Doc.&nbsp;</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách đ&ecirc;̉:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đánh giá vi&ecirc;̣c sử dụng các Trang Web CFS3Doc, các sản ph&acirc;̉m và dịch vụ</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>ph&acirc;n tích tính hi&ecirc;̣u quả của các quảng cáo, cu&ocirc;̣c thi và chương trình khuy&ecirc;́n m&atilde;i của chúng t&ocirc;i</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>cá nh&acirc;n hóa trải nghi&ecirc;̣m trang web của quý khách, đ&ocirc;̀ng thời đánh giá (&acirc;̉n danh và t&ocirc;̉ng th&ecirc;̉) các s&ocirc;́ li&ecirc;̣u th&ocirc;́ng k&ecirc; v&ecirc;̀ hoạt đ&ocirc;̣ng của trang web, chẳng hạn như thời gian quý khách ghé thăm, li&ecirc;̣u quý khách đã từng ghé thăm trang web này trước đó kh&ocirc;ng và trang web nào giới thi&ecirc;̣u quý khách đăng nh&acirc;̣p vào đó</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>giúp d&ecirc;̃ dàng sử dụng các Trang Web CFS3Doc và đi&ecirc;̀u chỉnh hi&ecirc;̣u quả các Trang Web CFS3Doc cũng như các sản ph&acirc;̉m của chúng t&ocirc;i theo sở thích và nhu c&acirc;̀u của quý khách</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>giúp thúc đ&acirc;̉y các hoạt đ&ocirc;̣ng trong tương lai của quý khách và trải nghi&ecirc;̣m v&ecirc;̀ các Trang Web CFS3Doc. Ví dụ, m&ocirc;̣t trang có th&ecirc;̉ nh&acirc;̣n ra rằng quý khách đã cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n và sẽ kh&ocirc;ng y&ecirc;u c&acirc;̀u th&ocirc;ng tin đ&oacute; l&acirc;̀n thứ hai nữa</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>thu th&acirc;̣p th&ocirc;ng tin v&ecirc;̀ thi&ecirc;́t bị quý khách đang sử dụng đ&ecirc;̉ xem Trang Web CFS3Doc, chẳng hạn như địa chỉ IP của quý khách hay loại b&ocirc;̣ trình duy&ecirc;̣t Internet hay h&ecirc;̣ đi&ecirc;̀u hành quý khách đang sử dụng, và li&ecirc;n k&ecirc;́t chúng tới th&ocirc;ng tin cá nh&acirc;n của quý khách nhằm đảm bảo rằng m&ocirc;̃i Trang Web CFS3Doc th&ecirc;̉ hi&ecirc;̣n trải nghi&ecirc;̣m web t&ocirc;́t nh&acirc;́t cho quý khách</span></li>
    </ul>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ li&ecirc;n lạc với quý khách v&ecirc;̀ sản ph&acirc;̉m và dịch vụ mà quý khách có th&ecirc;̉ quan t&acirc;m, với đi&ecirc;̀u ki&ecirc;̣n quý khách đ&ocirc;̀ng ý cho chúng t&ocirc;i làm như v&acirc;̣y hay trước đó quý khách đã y&ecirc;u c&acirc;̀u sản ph&acirc;̉m hay dịch vụ từ chúng t&ocirc;i và th&ocirc;ng tin li&ecirc;n lạc li&ecirc;n quan đ&ecirc;́n y&ecirc;u c&acirc;̀u trước đó và được l&acirc;̣p trong b&acirc;́t kỳ khung thời gian nào được lu&acirc;̣t pháp áp dụng quy định.&nbsp;</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách đ&ecirc;̉:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>giới thi&ecirc;̣u các sản ph&acirc;̉m hay dịch vụ (bao g&ocirc;̀m những sản ph&acirc;̉m của các b&ecirc;n thứ ba li&ecirc;n quan) mà chúng t&ocirc;i cho rằng quý khách quan t&acirc;m.</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>trao cho quý khách cơ h&ocirc;̣i tham gia vào các cu&ocirc;̣c thi hay chương trình khuy&ecirc;́n m&atilde;i</span></li>
    </ul>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Quý khách có th&ecirc;̉ quy&ecirc;́t định kh&ocirc;ng ti&ecirc;́p nh&acirc;̣n th&ocirc;ng tin từ chúng t&ocirc;i vào b&acirc;́t kỳ thời đi&ecirc;̉m nào. B&acirc;́t kỳ th&ocirc;ng tin tiếp thị trực ti&ecirc;́p nào mà chúng t&ocirc;i gửi cho quý khách sẽ cung c&acirc;́p cho quý khách th&ocirc;ng tin và phương ti&ecirc;̣n c&acirc;̀n thi&ecirc;́t đ&ecirc;̉ từ ch&ocirc;́i.</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ cung c&acirc;́p cho quý khách các sản ph&acirc;̉m hay dịch vụ quý khách y&ecirc;u c&acirc;̀u từ chúng t&ocirc;i.&nbsp;</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ phục vụ mục đích của các cu&ocirc;̣c thi hay chương trình khuy&ecirc;́n m&atilde;i mà quý khách đã tham gia</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ gửi cho quý khách th&ocirc;ng tin, sản ph&acirc;̉m hay m&acirc;̃u mà quý khách y&ecirc;u c&acirc;̀u</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ đáp ứng các y&ecirc;u c&acirc;̀u hay nh&acirc;̣n xét của quý khách</span></li>
    </ul>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>N&ecirc;́u chúng t&ocirc;i thu th&acirc;̣p th&ocirc;ng tin cá nh&acirc;n cho m&ocirc;̣t mục đích cụ th&ecirc;̉, chúng t&ocirc;i sẽ kh&ocirc;ng giữ th&ocirc;ng tin đó l&acirc;u hơn khoảng thời gian c&acirc;̀n thi&ecirc;́t của mục đích đó, trừ khi chúng t&ocirc;i phải giữ th&ocirc;ng tin vì các lý do kinh doanh hay pháp lý chính đáng. Đ&ecirc;̉ bảo v&ecirc;̣ th&ocirc;ng tin kh&ocirc;ng bị phá hoại m&ocirc;̣t cách v&ocirc; tình hay c&ocirc;́ ý, khi chúng t&ocirc;i xóa th&ocirc;ng tin khỏi dịch vụ của mình, chúng t&ocirc;i có th&ecirc;̉ kh&ocirc;ng xóa ngay các bản sao còn lại từ máy chủ hay xóa bỏ th&ocirc;ng tin từ h&ecirc;̣ th&ocirc;́ng sao lưu của chúng t&ocirc;i.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với ai?</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>V&ecirc;̀ nguy&ecirc;n tắc chung, chúng t&ocirc;i kh&ocirc;ng chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với b&acirc;́t kỳ ai ngoài CFS3Doc. Tuy nhi&ecirc;n, chúng t&ocirc;i có th&ecirc;̉ chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với các b&ecirc;n thứ ba đáng tin c&acirc;̣y.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các cơ quan quảng cáo, tiếp thị và khuy&ecirc;́n m&atilde;i đ&ecirc;̉ giúp chúng t&ocirc;i thực hiện và ph&acirc;n tích tính hi&ecirc;̣u quả của các chi&ecirc;́n lược quảng cáo và khuy&ecirc;́n m&atilde;i.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các b&ecirc;n thứ ba được y&ecirc;u c&acirc;̀u giao sản ph&acirc;̉m hay dịch vụ cho quý khách, chẳng hạn như giao hàng hay dịch vụ bưu chính chuy&ecirc;̉n phát sản ph&acirc;̉m mà quý khách đã đặt hàng</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>cơ quan cưỡng ch&ecirc;́ lu&acirc;̣t pháp hay cơ quan chính phủ tu&acirc;n thủ quy trình pháp lu&acirc;̣t thích hợp y&ecirc;u c&acirc;̀u chúng t&ocirc;i ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các b&ecirc;n thứ ba mu&ocirc;́n gửi cho quý khách th&ocirc;ng tin v&ecirc;̀ các sản ph&acirc;̉m và dịch vụ của họ, nhưng chỉ khi quý khách đã đ&ocirc;̀ng ý cho chúng t&ocirc;i làm như v&acirc;̣y</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các nhà cung c&acirc;́p dịch vụ b&ecirc;n thứ ba, chẳng hạn như xử lý dữ li&ecirc;̣u, cho CFS3Doc</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các nhà cung c&acirc;́p c&ocirc;ng cụ ph&acirc;n tích web, chẳng hạn như Google</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i cũng có th&ecirc;̉ chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với các c&ocirc;ng ty, t&ocirc;̉ chức hay cá nh&acirc;n b&ecirc;n ngoài CFS3Doc n&ecirc;́u chúng t&ocirc;i nghĩ rằng việc ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin n&agrave;y l&agrave; cần thiết vì c&aacute;c lý do hợp pháp.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách đ&ecirc;̉:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>thi hành các đi&ecirc;̀u khoản sử dụng áp dụng của các Trang Web CFS3Doc</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>tiến h&agrave;nh điều tra c&aacute;c vi phạm ph&aacute;p luật &aacute;p dụng c&oacute; thể c&oacute;</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>phát hi&ecirc;̣n, ngăn chặn và bảo v&ecirc;̣ ch&ocirc;́ng làm giả và các khả năng dễ bị thương tổn về an ninh hay kỹ thu&acirc;̣t</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>tu&acirc;n thủ pháp lu&acirc;̣t và quy định áp dụng, hợp tác trong b&acirc;́t kỳ vụ đi&ecirc;̀u tra pháp lý nào và đáp ứng các y&ecirc;u c&acirc;̀u của chính quy&ecirc;̀n</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>N&ecirc;́u chúng t&ocirc;i chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với m&ocirc;̣t b&ecirc;n thứ ba, chúng t&ocirc;i sẽ n&ocirc;̃ lực h&ecirc;́t sức đ&ecirc;̉ đảm bảo rằng họ sẽ bảo m&acirc;̣t th&ocirc;ng tin của quý khách, thực hi&ecirc;̣n mọi bi&ecirc;̣n pháp thích hợp đ&ecirc;̉ bảo v&ecirc;̣ ch&ocirc;́ng lạm dụng th&ocirc;ng tin và chỉ sử dụng th&ocirc;ng tin theo cách th&ocirc;́ng nh&acirc;́t với Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này và lu&acirc;̣t pháp và quy định bảo v&ecirc;̣ dữ li&ecirc;̣u áp dụng.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>CFS3Doc kh&ocirc;ng bán th&ocirc;ng tin cá nh&acirc;n, trừ đơn vị mà chúng t&ocirc;i r&uacute;t lui t&acirc;́t cả hay m&ocirc;̣t ph&acirc;̀n hoạt đ&ocirc;̣ng kinh doanh của mình (ví dụ, li&ecirc;n quan tới vi&ecirc;̣c bán thương hi&ecirc;̣u của chúng t&ocirc;i), hay li&ecirc;n quan đ&ecirc;́n vi&ecirc;̣c sáp nh&acirc;̣p, hợp nh&acirc;́t, thay đ&ocirc;̉i quy&ecirc;̀n ki&ecirc;̉m soát, tái cơ c&acirc;́u hay thanh lý t&acirc;́t cả hay m&ocirc;̣t ph&acirc;̀n hoạt đ&ocirc;̣ng kinh doanh của chúng t&ocirc;i.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Chuy&ecirc;̉n giao th&ocirc;ng tin cá nh&acirc;n của quý khách</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ chuy&ecirc;̉n th&ocirc;ng tin cá nh&acirc;n của quý khách tới các máy chủ đặt b&ecirc;n ngoài qu&ocirc;́c gia mà quý khách đang sinh s&ocirc;́ng hoặc tới các c&ocirc;ng ty li&ecirc;n k&ecirc;́t hay các b&ecirc;n thứ ba đáng tin c&acirc;̣y khác nằm ở các nước khác sao cho họ có th&ecirc;̉ xử lý th&ocirc;ng tin cá nh&acirc;n thay mặt cho chúng t&ocirc;i. Bằng cách sử dụng Trang Web CFS3Doc hay nói cách khác cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n cho CFS3Doc, quý khách đã đ&ocirc;̀ng ý cho chúng t&ocirc;i làm như v&acirc;̣y theo các đi&ecirc;̀u khoản của Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư cũng như pháp lu&acirc;̣t và quy định v&ecirc;̀ bảo v&ecirc;̣ dữ li&ecirc;̣u áp dụng.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Quý khách phải nh&acirc;̣n thức được rằng nhi&ecirc;̀u qu&ocirc;́c gia kh&ocirc;ng th&ecirc;̉ bảo v&ecirc;̣ pháp lý th&ocirc;ng tin cá nh&acirc;n gi&ocirc;́ng như quý khách có th&ecirc;̉ nhận được tại đ&acirc;́t nước qu&ecirc; hương của m&igrave;nh. Trong khi th&ocirc;ng tin cá nh&acirc;n của quý khách nằm ở m&ocirc;̣t nước khác, tòa án, các cơ quan cưỡng ch&ecirc;́ thi hành lu&acirc;̣t và các cơ quan an ninh qu&ocirc;́c gia tại nước đó có th&ecirc;̉ truy c&acirc;̣p vào th&ocirc;ng tin này theo lu&acirc;̣t pháp của họ. Theo y&ecirc;u c&acirc;̀u truy c&acirc;̣p hợp pháp này, chúng t&ocirc;i cam k&ecirc;́t rằng b&acirc;́t kỳ ai xử lý th&ocirc;ng tin cá nh&acirc;n của quý khách b&ecirc;n ngoài đ&acirc;́t nước qu&ecirc; hương quý khách đ&ecirc;̀u phải áp dụng các bi&ecirc;̣n pháp bảo v&ecirc;̣ th&ocirc;ng tin và chỉ được phép xử lý th&ocirc;ng tin theo hướng dẫn của CFS3Doc.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Bảo v&ecirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i thực hi&ecirc;̣n mọi bi&ecirc;̣n pháp phòng ngừa thích hợp đ&ecirc;̉ bảo m&acirc;̣t th&ocirc;ng tin cá nh&acirc;n của quý khách đ&ocirc;̀ng thời y&ecirc;u c&acirc;̀u các b&ecirc;n thứ ba xử lý th&ocirc;ng tin cá nh&acirc;n cho chúng t&ocirc;i cũng phải làm tương tự như v&acirc;̣y. Vi&ecirc;̣c truy c&acirc;̣p vào th&ocirc;ng tin cá nh&acirc;n của quý khách bị giới hạn nhằm ngăn chặn truy c&acirc;̣p b&acirc;́t hợp pháp, thay đ&ocirc;̉i hay sử dụng sai mục đích và chỉ có nh&acirc;n vi&ecirc;n và đại lý của chúng t&ocirc;i mới được phép truy c&acirc;̣p tr&ecirc;n cơ sở c&acirc;̀n phải bi&ecirc;́t.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Quy&ecirc;̀n ri&ecirc;ng tư của quý khách và người li&ecirc;n hệ</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>N&ecirc;́u quý khách có b&acirc;́t kỳ thắc mắc, nh&acirc;̣n xét hay m&ocirc;́i quan ngại nào v&ecirc;̀ cách chúng t&ocirc;i xử lý th&ocirc;ng tin cá nh&acirc;n của quý khách, thì quý khách có th&ecirc;̉ li&ecirc;n h&ecirc;̣ với chúng t&ocirc;i bằng cách nh&acirc;́p vào li&ecirc;n kết&nbsp;</span><strong><span style='font-size:13px;font-family:"Arial",sans-serif;color:#007DBB;'>Li&ecirc;n H&ecirc;̣ với Chúng T&ocirc;i</span></strong><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>&nbsp;tr&ecirc;n Trang Web CFS3Doc hướng d&acirc;̃n quý khách tới Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này. Ngoài ra, vui lòng ghé thăm trang web <a href="http://tailieu.thpthahoacfs3.click/"><span style="color:#EE8F08;">tailieu.thpthhcfs3.click</span></a> chọn qu&ocirc;́c gia thích hợp và nh&acirc;́p vào li&ecirc;n kết&nbsp;</span><strong><span style='font-size:13px;font-family:"Arial",sans-serif;color:#007DBB;'>Li&ecirc;n H&ecirc;̣ với Chúng T&ocirc;i.</span></strong><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>&nbsp;Y&ecirc;u c&acirc;̀u của quý khách sẽ được chuy&ecirc;̉n tới c&ocirc;ng ty t&acirc;̣p đoàn CFS3Doc thích hợp.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Quý khách có quy&ecirc;̀n th&ocirc;ng báo cho chúng t&ocirc;i n&ecirc;́u quý khách:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>kh&ocirc;ng mu&ocirc;́n chúng t&ocirc;i li&ecirc;n h&ecirc;̣ trong tương lai</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>mu&ocirc;́n nh&acirc;̣n m&ocirc;̣t bản sao th&ocirc;ng tin cá nh&acirc;n mà chúng t&ocirc;i giữ v&ecirc;̀ quý khách</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>mu&ocirc;́n chúng t&ocirc;i chỉnh sửa, c&acirc;̣p nh&acirc;̣t, hay xóa bỏ th&ocirc;ng tin cá nh&acirc;n của quý khách trong h&ocirc;̀ sơ của chúng t&ocirc;i</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>mu&ocirc;́n báo cáo v&ecirc;̀ b&acirc;́t kỳ trường hợp nào lạm dụng th&ocirc;ng tin cá nh&acirc;n của quý khách</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Đ&ecirc;̉ h&ocirc;̃ trợ chúng t&ocirc;i giải quy&ecirc;́t thắc mắc của quý khách, vui lòng cung c&acirc;́p họ t&ecirc;n và th&ocirc;ng tin chi ti&ecirc;́t của quý khách.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;'>&nbsp;</p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><u><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>NGUY&Ecirc;N TẮC V&Ecirc;̀ QUY&Ecirc;̀N RI&Ecirc;NG TƯ CỦA CFS3DOC</span></u></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>CFS3Doc r&acirc;́t coi trọng quy&ecirc;̀n ri&ecirc;ng tư. Năm nguy&ecirc;n tắc dưới đ&acirc;y là cơ sở cho phương pháp ti&ecirc;́p c&acirc;̣n của chúng t&ocirc;i trong vi&ecirc;̣c t&ocirc;n trọng quy&ecirc;̀n ri&ecirc;ng tư của quý khách:</span></p>
<ol start="1" type="1" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Chúng t&ocirc;i đánh giá cao ni&ecirc;̀m tin quý khách dành cho chúng t&ocirc;i khi quý khách cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n cho chúng t&ocirc;i. Chúng t&ocirc;i sẽ lu&ocirc;n sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách m&ocirc;̣t cách ch&acirc;n thực và xứng đáng với ni&ecirc;̀m tin đó.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Quý khách có quy&ecirc;̀n tìm hi&ecirc;̉u th&ocirc;ng tin v&ecirc;̀ cách chúng t&ocirc;i sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách. Chúng t&ocirc;i sẽ lu&ocirc;n th&ocirc;ng báo rõ ràng với quý khách v&ecirc;̀ những th&ocirc;ng tin chúng t&ocirc;i thu th&acirc;̣p, những vi&ecirc;̣c chúng t&ocirc;i làm với th&ocirc;ng tin đó, đ&ocirc;́i tượng chúng t&ocirc;i chia sẻ và người quý khách c&acirc;̀n li&ecirc;n lạc trong trường hợp có b&acirc;́t kỳ mối quan ngại nào.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>N&ecirc;́u quý khách có b&acirc;́t kỳ mối quan ngại nào v&ecirc;̀ cách thức chúng t&ocirc;i sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách, chúng t&ocirc;i sẵn sàng hợp tác với quý khách đ&ecirc;̉ nhanh chóng giải quy&ecirc;́t những mối quan ngại đó.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Chúng t&ocirc;i sẽ thực hi&ecirc;̣n t&acirc;́t cả c&aacute;c bước hợp l&yacute; đ&ecirc;̉ bảo v&ecirc;̣ th&ocirc;ng tin của quý khách kh&ocirc;ng bị lạm dụng và bảo m&acirc;̣t th&ocirc;ng tin đó.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Chúng t&ocirc;i sẽ tu&acirc;n thủ theo t&acirc;́t cả các lu&acirc;̣t và quy định bảo v&ecirc;̣ dữ li&ecirc;̣u áp dụng đ&ocirc;̀ng thời sẽ hợp tác với các cơ quan bảo v&ecirc;̣ dữ li&ecirc;̣u. N&ecirc;́u kh&ocirc;ng có lu&acirc;̣t bảo v&ecirc;̣ dữ li&ecirc;̣u, chúng t&ocirc;i sẽ hành đ&ocirc;̣ng theo các nguy&ecirc;n tắc được c&ocirc;ng nh&acirc;̣n r&ocirc;̣ng rãi v&ecirc;̀ bảo v&ecirc;̣ dữ li&ecirc;̣u.</span></li>
</ol>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;text-align:center;line-height:normal;background:white;'><u><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>CHÍNH SÁCH V&Ecirc;̀ QUY&Ecirc;̀N RI&Ecirc;NG TƯ CỦA CFS3DOC</span></u></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><em><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>L&acirc;̀n C&acirc;̣p Nh&acirc;̣t G&acirc;̀n Đ&acirc;y Nh&acirc;́t: Tháng 9 Năm 2023</span></em></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>CFS3Doc cam k&ecirc;́t bảo v&ecirc;̣ quy&ecirc;̀n ri&ecirc;ng tư của quý khách và đảm bảo bảo v&ecirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách. Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này n&ecirc;u rõ những th&ocirc;ng tin cá nh&acirc;n chúng t&ocirc;i thu th&acirc;̣p và cách thức chúng t&ocirc;i sử dụng, ti&ecirc;́t l&ocirc;̣ và bảo vệ th&ocirc;ng tin đó.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Đ&ocirc;́i tượng áp dụng của Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này là gì?</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này áp dụng cho th&ocirc;ng tin cá nh&acirc;n được CFS3Doc thu th&acirc;̣p li&ecirc;n quan đ&ecirc;́n các dịch vụ m&agrave; Tập đo&agrave;n cung c&acirc;́p. Tìm hi&ecirc;̉u th&ecirc;m th&ocirc;ng tin v&ecirc;̀ CFS3Doc tại địa chỉ <a href="http://tailieu.thpthahoacfs3.click/ve-chung-toi"><span style="color:#EE8F08;">http://tailieu.thpthahoacfs3.click//ve-chung-toi.</span></a> Trang này trình bày th&ocirc;ng tin được thu th&acirc;̣p theo hình thức ngoại tuy&ecirc;́n và các trung t&acirc;m chăm sóc khách hàng của chúng t&ocirc;i, các chi&ecirc;́n dịch tiếp thị trực ti&ecirc;́p, hình thức rút thăm trúng thưởng và các cu&ocirc;̣c thi, cũng như hình thức thu th&acirc;̣p trực tuy&ecirc;́n th&ocirc;ng qua các trang web của chúng t&ocirc;i, các trang uy tín v&ecirc;̀ c&aacute;c nền tảng và chương trình ứng dụng của b&ecirc;n thứ ba được truy c&acirc;̣p hay sử dụng th&ocirc;ng qua những trang web hoặc nền tảng của b&ecirc;n thứ ba đó được CFS3Doc hoặc đại di&ecirc;̣n của CFS3Doc đi&ecirc;̀u hành (&ldquo;<strong>Các Trang Web của CFS3Doc</strong>&rdquo;). Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này dưới đ&acirc;y được k&ecirc;́t hợp và tạo thành m&ocirc;̣t ph&acirc;̀n của các đi&ecirc;̀u khoản và đi&ecirc;̀u ki&ecirc;̣n sử dụng Trang Web CFS3Doc ứng dụng. Đ&ecirc;̉ bi&ecirc;́t th&ocirc;ng tin v&ecirc;̀ vi&ecirc;̣c CFS3Doc chịu trách nhi&ecirc;̣m bảo vệ th&ocirc;ng tin cá nh&acirc;n của quý khách, xin xem <a href="http://tailieu.thpthahoacfs3.click/private-policy#rights"><strong><span style="color:#EE8F08;">Quy&ecirc;̀n bảo m&acirc;̣t của quý khách và người c&acirc;̀n li&ecirc;n h&ecirc;̣</span></strong></a> dưới đ&acirc;y.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này kh&ocirc;ng áp dụng đ&ocirc;́i với:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>th&ocirc;ng tin thu thập được từ các trang web, các nền tảng và/hoặc ứng dụng b&ecirc;n thứ ba (&ldquo;<strong>Các Trang Web B&ecirc;n Thứ Ba</strong>&rdquo;) mà chúng t&ocirc;i kh&ocirc;ng ki&ecirc;̉m soát;</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>th&ocirc;ng tin do các Trang Web B&ecirc;n Thứ Ba thu th&acirc;̣p mà quý khách có th&ecirc;̉ truy c&acirc;̣p qua các đường link vào các Trang Web của CFS3Doc; hay</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>băng r&ocirc;n quảng cáo, chương trình rút thăm trúng thưởng và các chương trình quảng cáo hay khuy&ecirc;́n m&atilde;i khác tr&ecirc;n các Trang Web của B&ecirc;n Thứ Ba mà chúng t&ocirc;i có th&ecirc;̉ tài trợ hay tham gia.</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Những Trang Web B&ecirc;n Thứ Ba này có th&ecirc;̉ có những chính sách v&ecirc;̀ quy&ecirc;̀n ri&ecirc;ng tư, các đi&ecirc;̀u khoản và đi&ecirc;̀u ki&ecirc;̣n ri&ecirc;ng của mình. Chúng t&ocirc;i khuy&ecirc;́n khích quý khách n&ecirc;n đọc trước khi sử dụng các Trang Web B&ecirc;n Thứ Ba này.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Sự đ&ocirc;̀ng ý của quý khách</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>CFS3Doc sẽ kh&ocirc;ng thu th&acirc;̣p, sử dụng hay ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách mà kh&ocirc;ng được sự đ&ocirc;̀ng ý của quý khách. Trong h&acirc;̀u h&ecirc;́t trường hợp, chúng t&ocirc;i sẽ xin phép quý khách m&ocirc;̣t cách rõ ràng nhưng, trong m&ocirc;̣t s&ocirc;́ trường hợp, chúng t&ocirc;i có th&ecirc;̉ suy lu&acirc;̣n v&ecirc;̀ sự đ&ocirc;̀ng ý từ những hành đ&ocirc;̣ng và hành vi của quý khách. Bằng cách sử dụng Trang Web CFS3Doc, quý khách đ&ocirc;̀ng ý cho phép CFS3Doc thu th&acirc;̣p, sử dụng và ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách theo Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ y&ecirc;u c&acirc;̀u quý khách cung c&acirc;́p sự đ&ocirc;̀ng thu&acirc;̣n b&ocirc;̉ sung n&ecirc;́u c&acirc;̀n sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách cho các mục đích kh&ocirc;ng được trình bày trong Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này. Quý khách kh&ocirc;ng bắt bu&ocirc;̣c phải đ&ocirc;̀ng ý, tuy nhi&ecirc;n n&ecirc;́u quý khách quy&ecirc;́t định kh&ocirc;ng đ&ocirc;̀ng ý thì khi đ&oacute; quý khách có th&ecirc;̉ bị hạn ch&ecirc;́ tham gia vào m&ocirc;̣t s&ocirc;́ hoạt đ&ocirc;̣ng. N&ecirc;́u quý khách đ&ocirc;̀ng ý b&ocirc;̉ sung, các đi&ecirc;̀u khoản của sự đ&ocirc;̀ng ý đ&oacute; sẽ được áp dụng trong trường hợp có b&acirc;́t kỳ xung đ&ocirc;̣t nào với các đi&ecirc;̀u khoản của Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>N&ecirc;́u quý khách kh&ocirc;ng đ&ocirc;̀ng ý với vi&ecirc;̣c thu th&acirc;̣p, sử dụng và ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách theo cách này, vui lòng kh&ocirc;ng sử dụng các Trang Web CFS3Doc hoặc quý khách phải cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n cho CFS3Doc.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i thu th&acirc;̣p những th&ocirc;ng tin nào?</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Trong Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này, &ldquo;th&ocirc;ng tin cá nh&acirc;n&rdquo; của quý khách có nghĩa là th&ocirc;ng tin hay mẩu th&ocirc;ng tin có th&ecirc;̉ giúp nh&acirc;̣n di&ecirc;̣n ra quý khách. V&ecirc;̀ cơ bản, đi&ecirc;̀u này bao g&ocirc;̀m những th&ocirc;ng tin như họ t&ecirc;n, địa chỉ, t&ecirc;n đăng nh&acirc;̣p, hình đại di&ecirc;̣n, địa chỉ email và s&ocirc;́ đi&ecirc;̣n thoại, nhưng cũng có th&ecirc;̉ bao g&ocirc;̀m các th&ocirc;ng tin khác chẳng hạn như địa chỉ IP, thói quen mua sắm, sở thích và th&ocirc;ng tin v&ecirc;̀ phong cách sống hay sở thích của quý khách chẳng hạn như sở thích ri&ecirc;ng và m&ocirc;́i quan t&acirc;m. Chúng t&ocirc;i có th&ecirc;̉ thu th&acirc;̣p th&ocirc;ng tin cá nh&acirc;n của qu&yacute; kh&aacute;ch từ nhi&ecirc;̀u ngu&ocirc;̀n khác nhau, bao g&ocirc;̀m:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'><a href="http://tailieu.thpthahoacfs3.click/private-policy#OLE_LINK4"><span style="color:#EE8F08;">Th&ocirc;ng tin quý khách cung c&acirc;́p trực ti&ecirc;́p cho chúng t&ocirc;i</span></a></span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ trực ti&ecirc;́p thu th&acirc;̣p th&ocirc;ng tin v&ecirc;̀ quý khách n&ecirc;́u quý khách cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n cho chúng t&ocirc;i, chẳng hạn như khi quý khách đăng ký tham gia chương trình rút thăm trúng thưởng hay các cu&ocirc;̣c thi, đăng k&yacute; đ&ecirc;̉ nh&acirc;̣n th&ocirc;ng tin, sử dụng đơn xin tham gia, mua sản ph&acirc;̉m hay dịch vụ từ chúng t&ocirc;i, đi&ecirc;̀n vào bảng đi&ecirc;̀u tra, hay đưa ra lời nh&acirc;̣n xét hay y&ecirc;u c&acirc;̀u. Những loại th&ocirc;ng tin chúng t&ocirc;i có th&ecirc;̉ thu th&acirc;̣p trực ti&ecirc;́p từ quý khách bao g&ocirc;̀m:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>t&ecirc;n của quý khách</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>địa chỉ email</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>t&ecirc;n đăng nhập</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>s&ocirc;́ đi&ecirc;̣n thoại</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>tu&ocirc;̉i</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>ngày sinh</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>giới tính</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>n&ocirc;̣i dung do người dùng khởi tạo, các bài đăng và các n&ocirc;̣i dung khác quý khách n&ocirc;̣p cho các Trang Web CFS3Doc</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>b&acirc;́t kỳ th&ocirc;ng tin cá nh&acirc;n nào khác mà quý khách tự nguyện cung c&acirc;́p cho chúng t&ocirc;i</span></li>
    </ul>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'><a href="http://tailieu.thpthahoacfs3.click/private-policy#OLE_LINK4"><span style="color:#EE8F08;">Th&ocirc;ng tin chúng t&ocirc;i tự đ&ocirc;̣ng thu th&acirc;̣p khi quý khách sử dụng các Trang Web CFS3Doc</span></a></span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i sử dụng cookies và các c&ocirc;ng cụ khác (chẳng hạn như c&ocirc;ng cụ ph&acirc;n tích web và thẻ đi&ecirc;̉m ảnh) đ&ecirc;̉ tự đ&ocirc;̣ng thu th&acirc;̣p th&ocirc;ng tin v&ecirc;̀ quý khách khi quý khách sử dụng các Trang Web CFS3Doc, t&ugrave;y theo các đi&ecirc;̀u khoản của Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này và các lu&acirc;̣t và quy định bảo vệ dữ li&ecirc;̣u áp dụng. Những loại th&ocirc;ng tin chúng t&ocirc;i có th&ecirc;̉ thu th&acirc;̣p tự đ&ocirc;̣ng bao g&ocirc;̀m:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>th&ocirc;ng tin v&ecirc;̀ ki&ecirc;̉u b&ocirc;̣ trình duy&ecirc;̣t quý khách sử dụng</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>chi ti&ecirc;́t v&ecirc;̀ các trang web mà quý khách đã xem</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>t&ecirc;n người dùng, hình đại di&ecirc;̣n, giới tính, mạng của quý khách và b&acirc;́t kỳ th&ocirc;ng tin nào khác mà quý khách chọn đ&ecirc;̉ chia sẻ khi dùng các Trang Web B&ecirc;n Thứ Ba (chẳng hạn khi quý khách dùng chức năng &ldquo;Like&rdquo; (thích) tr&ecirc;n Facebook hay chức năng +1 tr&ecirc;n Google+)</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>Các trang web quý khách đã ghé thăm trước khi truy c&acirc;̣p vào Trang Web CFS3Doc</span></li>
    </ul>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>H&acirc;̀u h&ecirc;́t các b&ocirc;̣ trình duy&ecirc;̣t internet được thi&ecirc;́t l&acirc;̣p ban đ&acirc;̀u đ&ecirc;̀u ch&acirc;́p nh&acirc;̣n cookies. Quý khách có th&ecirc;̉ thay đ&ocirc;̉i thiết lập đ&ecirc;̉ chặn các cookies hoặc cảnh báo quý khách khi các cookies được gửi tới thi&ecirc;́t bị của quý khách. N&ecirc;́u quý khách tắt cookies, đi&ecirc;̀u này sẽ ảnh hưởng đ&ecirc;́n trải nghi&ecirc;̣m của quý khách tr&ecirc;n các Trang Web CFS3Doc.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách như th&ecirc;́ nào?</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ cải ti&ecirc;́n sản ph&acirc;̉m của chúng t&ocirc;i và n&acirc;ng cao trải nghi&ecirc;̣m của quý khách tr&ecirc;n các Trang Web CFS3Doc.&nbsp;</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách đ&ecirc;̉:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đánh giá vi&ecirc;̣c sử dụng các Trang Web CFS3Doc, các sản ph&acirc;̉m và dịch vụ</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>ph&acirc;n tích tính hi&ecirc;̣u quả của các quảng cáo, cu&ocirc;̣c thi và chương trình khuy&ecirc;́n m&atilde;i của chúng t&ocirc;i</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>cá nh&acirc;n hóa trải nghi&ecirc;̣m trang web của quý khách, đ&ocirc;̀ng thời đánh giá (&acirc;̉n danh và t&ocirc;̉ng th&ecirc;̉) các s&ocirc;́ li&ecirc;̣u th&ocirc;́ng k&ecirc; v&ecirc;̀ hoạt đ&ocirc;̣ng của trang web, chẳng hạn như thời gian quý khách ghé thăm, li&ecirc;̣u quý khách đã từng ghé thăm trang web này trước đó kh&ocirc;ng và trang web nào giới thi&ecirc;̣u quý khách đăng nh&acirc;̣p vào đó</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>giúp d&ecirc;̃ dàng sử dụng các Trang Web CFS3Doc và đi&ecirc;̀u chỉnh hi&ecirc;̣u quả các Trang Web CFS3Doc cũng như các sản ph&acirc;̉m của chúng t&ocirc;i theo sở thích và nhu c&acirc;̀u của quý khách</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>giúp thúc đ&acirc;̉y các hoạt đ&ocirc;̣ng trong tương lai của quý khách và trải nghi&ecirc;̣m v&ecirc;̀ các Trang Web CFS3Doc. Ví dụ, m&ocirc;̣t trang có th&ecirc;̉ nh&acirc;̣n ra rằng quý khách đã cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n và sẽ kh&ocirc;ng y&ecirc;u c&acirc;̀u th&ocirc;ng tin đ&oacute; l&acirc;̀n thứ hai nữa</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>thu th&acirc;̣p th&ocirc;ng tin v&ecirc;̀ thi&ecirc;́t bị quý khách đang sử dụng đ&ecirc;̉ xem Trang Web CFS3Doc, chẳng hạn như địa chỉ IP của quý khách hay loại b&ocirc;̣ trình duy&ecirc;̣t Internet hay h&ecirc;̣ đi&ecirc;̀u hành quý khách đang sử dụng, và li&ecirc;n k&ecirc;́t chúng tới th&ocirc;ng tin cá nh&acirc;n của quý khách nhằm đảm bảo rằng m&ocirc;̃i Trang Web CFS3Doc th&ecirc;̉ hi&ecirc;̣n trải nghi&ecirc;̣m web t&ocirc;́t nh&acirc;́t cho quý khách</span></li>
    </ul>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ li&ecirc;n lạc với quý khách v&ecirc;̀ sản ph&acirc;̉m và dịch vụ mà quý khách có th&ecirc;̉ quan t&acirc;m, với đi&ecirc;̀u ki&ecirc;̣n quý khách đ&ocirc;̀ng ý cho chúng t&ocirc;i làm như v&acirc;̣y hay trước đó quý khách đã y&ecirc;u c&acirc;̀u sản ph&acirc;̉m hay dịch vụ từ chúng t&ocirc;i và th&ocirc;ng tin li&ecirc;n lạc li&ecirc;n quan đ&ecirc;́n y&ecirc;u c&acirc;̀u trước đó và được l&acirc;̣p trong b&acirc;́t kỳ khung thời gian nào được lu&acirc;̣t pháp áp dụng quy định.&nbsp;</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách đ&ecirc;̉:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>giới thi&ecirc;̣u các sản ph&acirc;̉m hay dịch vụ (bao g&ocirc;̀m những sản ph&acirc;̉m của các b&ecirc;n thứ ba li&ecirc;n quan) mà chúng t&ocirc;i cho rằng quý khách quan t&acirc;m.</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>trao cho quý khách cơ h&ocirc;̣i tham gia vào các cu&ocirc;̣c thi hay chương trình khuy&ecirc;́n m&atilde;i</span></li>
    </ul>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Quý khách có th&ecirc;̉ quy&ecirc;́t định kh&ocirc;ng ti&ecirc;́p nh&acirc;̣n th&ocirc;ng tin từ chúng t&ocirc;i vào b&acirc;́t kỳ thời đi&ecirc;̉m nào. B&acirc;́t kỳ th&ocirc;ng tin tiếp thị trực ti&ecirc;́p nào mà chúng t&ocirc;i gửi cho quý khách sẽ cung c&acirc;́p cho quý khách th&ocirc;ng tin và phương ti&ecirc;̣n c&acirc;̀n thi&ecirc;́t đ&ecirc;̉ từ ch&ocirc;́i.</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ cung c&acirc;́p cho quý khách các sản ph&acirc;̉m hay dịch vụ quý khách y&ecirc;u c&acirc;̀u từ chúng t&ocirc;i.&nbsp;</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:.5in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ sử dụng th&ocirc;ng tin cá nh&acirc;n của quý khách:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <ul type="circle" style="margin-bottom:0in;">
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ phục vụ mục đích của các cu&ocirc;̣c thi hay chương trình khuy&ecirc;́n m&atilde;i mà quý khách đã tham gia</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ gửi cho quý khách th&ocirc;ng tin, sản ph&acirc;̉m hay m&acirc;̃u mà quý khách y&ecirc;u c&acirc;̀u</span></li>
        <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>đ&ecirc;̉ đáp ứng các y&ecirc;u c&acirc;̀u hay nh&acirc;̣n xét của quý khách</span></li>
    </ul>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>N&ecirc;́u chúng t&ocirc;i thu th&acirc;̣p th&ocirc;ng tin cá nh&acirc;n cho m&ocirc;̣t mục đích cụ th&ecirc;̉, chúng t&ocirc;i sẽ kh&ocirc;ng giữ th&ocirc;ng tin đó l&acirc;u hơn khoảng thời gian c&acirc;̀n thi&ecirc;́t của mục đích đó, trừ khi chúng t&ocirc;i phải giữ th&ocirc;ng tin vì các lý do kinh doanh hay pháp lý chính đáng. Đ&ecirc;̉ bảo v&ecirc;̣ th&ocirc;ng tin kh&ocirc;ng bị phá hoại m&ocirc;̣t cách v&ocirc; tình hay c&ocirc;́ ý, khi chúng t&ocirc;i xóa th&ocirc;ng tin khỏi dịch vụ của mình, chúng t&ocirc;i có th&ecirc;̉ kh&ocirc;ng xóa ngay các bản sao còn lại từ máy chủ hay xóa bỏ th&ocirc;ng tin từ h&ecirc;̣ th&ocirc;́ng sao lưu của chúng t&ocirc;i.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với ai?</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>V&ecirc;̀ nguy&ecirc;n tắc chung, chúng t&ocirc;i kh&ocirc;ng chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với b&acirc;́t kỳ ai ngoài CFS3Doc. Tuy nhi&ecirc;n, chúng t&ocirc;i có th&ecirc;̉ chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với các b&ecirc;n thứ ba đáng tin c&acirc;̣y.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các cơ quan quảng cáo, tiếp thị và khuy&ecirc;́n m&atilde;i đ&ecirc;̉ giúp chúng t&ocirc;i thực hiện và ph&acirc;n tích tính hi&ecirc;̣u quả của các chi&ecirc;́n lược quảng cáo và khuy&ecirc;́n m&atilde;i.</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các b&ecirc;n thứ ba được y&ecirc;u c&acirc;̀u giao sản ph&acirc;̉m hay dịch vụ cho quý khách, chẳng hạn như giao hàng hay dịch vụ bưu chính chuy&ecirc;̉n phát sản ph&acirc;̉m mà quý khách đã đặt hàng</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>cơ quan cưỡng ch&ecirc;́ lu&acirc;̣t pháp hay cơ quan chính phủ tu&acirc;n thủ quy trình pháp lu&acirc;̣t thích hợp y&ecirc;u c&acirc;̀u chúng t&ocirc;i ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các b&ecirc;n thứ ba mu&ocirc;́n gửi cho quý khách th&ocirc;ng tin v&ecirc;̀ các sản ph&acirc;̉m và dịch vụ của họ, nhưng chỉ khi quý khách đã đ&ocirc;̀ng ý cho chúng t&ocirc;i làm như v&acirc;̣y</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các nhà cung c&acirc;́p dịch vụ b&ecirc;n thứ ba, chẳng hạn như xử lý dữ li&ecirc;̣u, cho CFS3Doc</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>các nhà cung c&acirc;́p c&ocirc;ng cụ ph&acirc;n tích web, chẳng hạn như Google</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i cũng có th&ecirc;̉ chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với các c&ocirc;ng ty, t&ocirc;̉ chức hay cá nh&acirc;n b&ecirc;n ngoài CFS3Doc n&ecirc;́u chúng t&ocirc;i nghĩ rằng việc ti&ecirc;́t l&ocirc;̣ th&ocirc;ng tin n&agrave;y l&agrave; cần thiết vì c&aacute;c lý do hợp pháp.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách đ&ecirc;̉:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>thi hành các đi&ecirc;̀u khoản sử dụng áp dụng của các Trang Web CFS3Doc</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>tiến h&agrave;nh điều tra c&aacute;c vi phạm ph&aacute;p luật &aacute;p dụng c&oacute; thể c&oacute;</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>phát hi&ecirc;̣n, ngăn chặn và bảo v&ecirc;̣ ch&ocirc;́ng làm giả và các khả năng dễ bị thương tổn về an ninh hay kỹ thu&acirc;̣t</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>tu&acirc;n thủ pháp lu&acirc;̣t và quy định áp dụng, hợp tác trong b&acirc;́t kỳ vụ đi&ecirc;̀u tra pháp lý nào và đáp ứng các y&ecirc;u c&acirc;̀u của chính quy&ecirc;̀n</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>N&ecirc;́u chúng t&ocirc;i chia sẻ th&ocirc;ng tin cá nh&acirc;n của quý khách với m&ocirc;̣t b&ecirc;n thứ ba, chúng t&ocirc;i sẽ n&ocirc;̃ lực h&ecirc;́t sức đ&ecirc;̉ đảm bảo rằng họ sẽ bảo m&acirc;̣t th&ocirc;ng tin của quý khách, thực hi&ecirc;̣n mọi bi&ecirc;̣n pháp thích hợp đ&ecirc;̉ bảo v&ecirc;̣ ch&ocirc;́ng lạm dụng th&ocirc;ng tin và chỉ sử dụng th&ocirc;ng tin theo cách th&ocirc;́ng nh&acirc;́t với Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này và lu&acirc;̣t pháp và quy định bảo v&ecirc;̣ dữ li&ecirc;̣u áp dụng.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>CFS3Doc kh&ocirc;ng bán th&ocirc;ng tin cá nh&acirc;n, trừ đơn vị mà chúng t&ocirc;i r&uacute;t lui t&acirc;́t cả hay m&ocirc;̣t ph&acirc;̀n hoạt đ&ocirc;̣ng kinh doanh của mình (ví dụ, li&ecirc;n quan tới vi&ecirc;̣c bán thương hi&ecirc;̣u của chúng t&ocirc;i), hay li&ecirc;n quan đ&ecirc;́n vi&ecirc;̣c sáp nh&acirc;̣p, hợp nh&acirc;́t, thay đ&ocirc;̉i quy&ecirc;̀n ki&ecirc;̉m soát, tái cơ c&acirc;́u hay thanh lý t&acirc;́t cả hay m&ocirc;̣t ph&acirc;̀n hoạt đ&ocirc;̣ng kinh doanh của chúng t&ocirc;i.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Chuy&ecirc;̉n giao th&ocirc;ng tin cá nh&acirc;n của quý khách</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i có th&ecirc;̉ chuy&ecirc;̉n th&ocirc;ng tin cá nh&acirc;n của quý khách tới các máy chủ đặt b&ecirc;n ngoài qu&ocirc;́c gia mà quý khách đang sinh s&ocirc;́ng hoặc tới các c&ocirc;ng ty li&ecirc;n k&ecirc;́t hay các b&ecirc;n thứ ba đáng tin c&acirc;̣y khác nằm ở các nước khác sao cho họ có th&ecirc;̉ xử lý th&ocirc;ng tin cá nh&acirc;n thay mặt cho chúng t&ocirc;i. Bằng cách sử dụng Trang Web CFS3Doc hay nói cách khác cung c&acirc;́p th&ocirc;ng tin cá nh&acirc;n cho CFS3Doc, quý khách đã đ&ocirc;̀ng ý cho chúng t&ocirc;i làm như v&acirc;̣y theo các đi&ecirc;̀u khoản của Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư cũng như pháp lu&acirc;̣t và quy định v&ecirc;̀ bảo v&ecirc;̣ dữ li&ecirc;̣u áp dụng.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Quý khách phải nh&acirc;̣n thức được rằng nhi&ecirc;̀u qu&ocirc;́c gia kh&ocirc;ng th&ecirc;̉ bảo v&ecirc;̣ pháp lý th&ocirc;ng tin cá nh&acirc;n gi&ocirc;́ng như quý khách có th&ecirc;̉ nhận được tại đ&acirc;́t nước qu&ecirc; hương của m&igrave;nh. Trong khi th&ocirc;ng tin cá nh&acirc;n của quý khách nằm ở m&ocirc;̣t nước khác, tòa án, các cơ quan cưỡng ch&ecirc;́ thi hành lu&acirc;̣t và các cơ quan an ninh qu&ocirc;́c gia tại nước đó có th&ecirc;̉ truy c&acirc;̣p vào th&ocirc;ng tin này theo lu&acirc;̣t pháp của họ. Theo y&ecirc;u c&acirc;̀u truy c&acirc;̣p hợp pháp này, chúng t&ocirc;i cam k&ecirc;́t rằng b&acirc;́t kỳ ai xử lý th&ocirc;ng tin cá nh&acirc;n của quý khách b&ecirc;n ngoài đ&acirc;́t nước qu&ecirc; hương quý khách đ&ecirc;̀u phải áp dụng các bi&ecirc;̣n pháp bảo v&ecirc;̣ th&ocirc;ng tin và chỉ được phép xử lý th&ocirc;ng tin theo hướng dẫn của CFS3Doc.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Bảo v&ecirc;̣ th&ocirc;ng tin cá nh&acirc;n của quý khách</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Chúng t&ocirc;i thực hi&ecirc;̣n mọi bi&ecirc;̣n pháp phòng ngừa thích hợp đ&ecirc;̉ bảo m&acirc;̣t th&ocirc;ng tin cá nh&acirc;n của quý khách đ&ocirc;̀ng thời y&ecirc;u c&acirc;̀u các b&ecirc;n thứ ba xử lý th&ocirc;ng tin cá nh&acirc;n cho chúng t&ocirc;i cũng phải làm tương tự như v&acirc;̣y. Vi&ecirc;̣c truy c&acirc;̣p vào th&ocirc;ng tin cá nh&acirc;n của quý khách bị giới hạn nhằm ngăn chặn truy c&acirc;̣p b&acirc;́t hợp pháp, thay đ&ocirc;̉i hay sử dụng sai mục đích và chỉ có nh&acirc;n vi&ecirc;n và đại lý của chúng t&ocirc;i mới được phép truy c&acirc;̣p tr&ecirc;n cơ sở c&acirc;̀n phải bi&ecirc;́t.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:3.75pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:30px;font-family:"Arial",sans-serif;color:black;'>Quy&ecirc;̀n ri&ecirc;ng tư của quý khách và người li&ecirc;n hệ</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>N&ecirc;́u quý khách có b&acirc;́t kỳ thắc mắc, nh&acirc;̣n xét hay m&ocirc;́i quan ngại nào v&ecirc;̀ cách chúng t&ocirc;i xử lý th&ocirc;ng tin cá nh&acirc;n của quý khách, thì quý khách có th&ecirc;̉ li&ecirc;n h&ecirc;̣ với chúng t&ocirc;i bằng cách nh&acirc;́p vào li&ecirc;n kết&nbsp;</span><strong><span style='font-size:13px;font-family:"Arial",sans-serif;color:#007DBB;'>Li&ecirc;n H&ecirc;̣ với Chúng T&ocirc;i</span></strong><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>&nbsp;tr&ecirc;n Trang Web CFS3Doc hướng d&acirc;̃n quý khách tới Chính Sách v&ecirc;̀ Quy&ecirc;̀n Ri&ecirc;ng Tư này. Ngoài ra, vui lòng ghé thăm trang web <a href="http://tailieu.thpthahoacfs3.click/"><span style="color:#EE8F08;">tailieu.thpthhcfs3.click</span></a> chọn qu&ocirc;́c gia thích hợp và nh&acirc;́p vào li&ecirc;n kết&nbsp;</span><strong><span style='font-size:13px;font-family:"Arial",sans-serif;color:#007DBB;'>Li&ecirc;n H&ecirc;̣ với Chúng T&ocirc;i.</span></strong><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>&nbsp;Y&ecirc;u c&acirc;̀u của quý khách sẽ được chuy&ecirc;̉n tới c&ocirc;ng ty t&acirc;̣p đoàn CFS3Doc thích hợp.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Quý khách có quy&ecirc;̀n th&ocirc;ng báo cho chúng t&ocirc;i n&ecirc;́u quý khách:</span></p>
<ul type="disc" style="margin-bottom:0in;">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>kh&ocirc;ng mu&ocirc;́n chúng t&ocirc;i li&ecirc;n h&ecirc;̣ trong tương lai</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>mu&ocirc;́n nh&acirc;̣n m&ocirc;̣t bản sao th&ocirc;ng tin cá nh&acirc;n mà chúng t&ocirc;i giữ v&ecirc;̀ quý khách</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>mu&ocirc;́n chúng t&ocirc;i chỉnh sửa, c&acirc;̣p nh&acirc;̣t, hay xóa bỏ th&ocirc;ng tin cá nh&acirc;n của quý khách trong h&ocirc;̀ sơ của chúng t&ocirc;i</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;color:black;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;'>mu&ocirc;́n báo cáo v&ecirc;̀ b&acirc;́t kỳ trường hợp nào lạm dụng th&ocirc;ng tin cá nh&acirc;n của quý khách</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:15.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;line-height:normal;background:white;'><span style='font-size:13px;font-family:"Arial",sans-serif;color:black;'>Đ&ecirc;̉ h&ocirc;̃ trợ chúng t&ocirc;i giải quy&ecirc;́t thắc mắc của quý khách, vui lòng cung c&acirc;́p họ t&ecirc;n và th&ocirc;ng tin chi ti&ecirc;́t của quý khách.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;font-size:14.0pt;font-family:"Times New Roman",serif;'>&nbsp;</p>



    
</body>
</html>