version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php-apache2
            dockerfile: Dockerfile
        depends_on:
          - db
        volumes:
            - ./sources/:/var/www/html/
        ports:
            - 8000:80
            
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql12345
            MYSQL_DATABASE: tailieu_cfs3
            MYSQL_USER: chukiet2001
            MYSQL_PASSWORD: mysql12345
        ports:
            - "9906:3306"
        volumes: 
            - ./sources/database/tailieu_cfs3.sql:/docker-entrypoint-initdb.d/dump.sql
        
    phpmyadmin:
        container_name: pma
        links:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        

